const DataProject = [
  {
    src: '/img/film-flix.png',
    alt: 'Imagem ilustrativa da página de filmes',
    title: 'Página de filmes',
    h3: 'Film Flix',
    p: 'Página de filmes. Tenha acesso as informações do melhores filmes lançados, seu orçamento, receita e uma breve descrição.',
    href_site: 'https://film-flix-two.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/hydrahtec/Projetos/tree/main/film_flix',
    txt_git: 'Código',
  },
  {
    src: '/img/cadastro.png',
    alt: 'Imagem ilustrativa da pagina de cadastro de cides e pessoas',
    title: 'Pagina de cadastro de cidades e pessoas',
    h3: 'Cadastro',
    p: 'Página desenvolvida para cadastrar informações sobre pessoas e cidades e possibilitar uma busca personalizada com paginação.',
    href_site: 'https://cadastro-kohl.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/hydrahtec/Projetos/tree/main/cadastros',
    txt_git: 'Código',
  },
  {
    src: '/img/login-cadastro.png',
    alt: 'Imagem ilustrativa da página de login',
    title: 'Página de login e cadastro',
    h3: 'Página de login',
    p: 'Página de cadastro de usuários e login de acesso.',
    href_site: 'https://login-cadastro-wheat.vercel.app/',
    txt_site: 'Site',
    href_git: 'https://github.com/hydrahtec/Projetos/tree/main/login-cadastro',
    txt_git: 'Código',
  },
  {
    src: '/img/padaria-plus.png',
    alt: 'Imagem ilustrativa do projeto padaria plus',
    title: 'padaria plus',
    h3: 'Padaria Plus',
    p: 'O melhor de nossos pães e bolos para você. Desde 2001, o lugar mais gostoso da cidade.',
    href_site: 'https://hydrahtec.com/padaria-plus/',
    txt_site: 'Site',
    href_git:
      'https://github.com/hydrahtec/devmedia_curso/tree/main/html/projetos%20html/padaria%20plus',
    txt_git: 'Código',
  },
  {
    src: 'img/imobiliaria-santos.png',
    alt: 'Imagem ilustrativa do projeto imobiliária santos',
    title: 'imobiliária santos',
    h3: 'Imobiliária Santos',
    p: 'Há 10 anos no ramo conquistando a confiança de inúmeros clientes.',
    href_site: 'https://hydrahtec.com/imobiliaria-santos/',
    txt_site: 'Site',
    href_git:
      'https://github.com/hydrahtec/devmedia_curso/tree/main/html/projetos%20html/imobiliaria-santos',
    txt_git: 'Código',
  },
  {
    src: '/img/alucar.png',
    alt: 'Imagem ilustrativa de projeto Alucar - aluguel de carros',
    title: 'Alucar - aluguel de carros',
    h3: 'Alucar',
    p: 'Há 45 anos atuando na área de locação de veículos com segurança e garantia de satisfação.',
    href_site: 'https://hydrahtec.com/alucar/',
    txt_site: 'Site',
    href_git:
      'https://github.com/hydrahtec/devmedia_curso/tree/main/html/teste/Alucar',
    txt_git: 'Código',
  },
  {
    src: '/img/advocacia.png',
    alt: 'Imagem ilustrativa do projeto advocacia - Senhor lei',
    title: 'advocacia - Senhor lei',
    h3: 'Advocacia Senhor lei',
    p: 'Há 30 anos atuando em diversas áreas legais sempre com princípios e valores.',
    href_site: 'https://hydrahtec.com/advocacia/',
    txt_site: 'Site',
    href_git:
      'https://github.com/hydrahtec/devmedia_curso/tree/main/html/projetos%20css/advocacia',
    txt_git: 'Código',
  },
  {
    src: '/img/img-card.png',
    alt: 'Imagem ilustrativa de projetos em andamento',
    title: 'Projeto em andamento',
    h3: 'Em breve',
    p: 'Trabalho em andamento',
    href_site: '/',
    txt_site: 'Site',
    href_git: '/',
    txt_git: 'Código',
  },
  {
    src: '/img/img-card.png',
    alt: 'Imagem ilustrativa de projetos em andamento',
    title: 'Projeto em andamento',
    h3: 'Em breve',
    p: 'Trabalho em andamento',
    href_site: '/',
    txt_site: 'Site',
    href_git: '/',
    txt_git: 'Código',
  },
];

export default DataProject;
